# Generated by Django 2.1.15 on 2019-12-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('b_address', models.CharField(max_length=200)),
                ('b_postal', models.CharField(max_length=50)),
                ('b_city', models.CharField(max_length=50)),
                ('c_phone', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(max_length=100)),
                ('open_time', models.TimeField()),
                ('d_desc', models.CharField(max_length=50)),
            ],
        ),
    ]
